apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-rknop-20240828
  namespace: romansnpit-roman-desc-simdex
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: nfs-client
  volumeMode: Filesystem
